### ISSUE TITLE
a WARNING that came up and included "consider notifying the package maintainer" 

### ISSUE THREAD

**Issue by bmillerlab** [conda-forge/pyhum-feedstock#12]
Issue when trying to fix qiime2 by reinstalling because it was not working correctly on my macbook pro.   Command I ran:

$conda env remove -n qiime2-2017.10

It was apparently working but then this came up:

WARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::widgetsnbextension-3.0.6-py35_0
consider notifying the package maintainer

**Comment by ocefpaf** [comment]
The warning is regarding `widgetsnbextension` and the package you removed was `qiime2`. Both have nothing to do with `pyhum`. Closing this.

PS: the warning is innocuous as far as I know.
